### ISSUE TITLE
How to get current spot price

### ISSUE THREAD

**Issue by Avec112** [kjeet90/homey-power-of-the-hour#101]
Hi Kjetil. 

This is not an issue, but more a question for how to setup you app correctly. 

Ref.
![image](https://github.com/kjeet90/homey-power-of-the-hour/assets/5219735/ecb03168-07ea-436d-bdc8-dd47bf70486d)

How can i get the current power price to set up correctly in Homey flow?  I use EVA Han-port meter reader and i have Elvia as grid owner. Fjordkraft is my power company. 

It seems that Tibber Pulse delivers price for it's consumers. How can I get the price and is it if even possible?

**Comment by kjeet90** [comment]
You need to use an app that can fetch the power price and update POTH with it. For example one of these two:

https://homey.app/no-no/app/com.gruijter.powerhour/Power-by-the-Hour/

https://homey.app/no-no/app/no.almli.utilitycost/Str%C3%B8mregning/

**Comment by Avec112** [comment]
Aha. I have downloaded both of them already so I hoped that maybe one of them could give med the answer. 

It seems `Power By the Hour` seems to be the one. 

**Tip!** Maybe add some text with hint to where the user can find the current price in your readme? :-) This would be very helpful. 

Thanks!

**Comment by Avec112** [comment]
Haha...your edit updated at the same time I posted. Spot on 💯
