### ISSUE TITLE
Adding device results in no new device

### ISSUE THREAD

**Issue by asjafjell** [kjeet90/homey-power-of-the-hour#77]
Hi, looks like everyone is using this app without any problems, so this may be a user problem. 

I am adding a POTH-device by selecting the new device found and adding it. It does not show up under my devices. I have tried resetting the app and restarting my Homey without luck. Are there any known issues? 

Regards, Alex

**Comment by kjeet90** [comment]
Hei

Går ut ifra at du er norsk basert på etternavnet.

Når du går gjennom "Legg til enhet"-menyen, så kommer det opp "Legger til
enhet" en stund før det forsvinner, men ingen ny enhet blir lagt til?
Hvilken firmware-versjon er Homeyen? Jeg prøvde nettopp å legge til en ny
enhet selv og det funket. Har aldri hørt om dette problemet før, dessverre.

Finner du enheten her inne etter du har forsøkt å legge den til?
https://tools.developer.homey.app/tools/devices



Mvh
Kjetil Haugland


ons. 11. jan. 2023, 21:35 skrev Aleksander Sjåfjell <
***@***.***>:

**Comment by asjafjell** [comment]
After a bit of debugging and hair-pulling, I have found that this is a GUI-bug in the Homey app. Adding it through web solves it. The device is invisible on my phone, but added successfully and visible on web.
